[build]
  publish = "build"
  command = """
    curl -sSL https://install.python-poetry.org | python3 -
    pip install --upgrade pip
    pip install -r requirements.txt
    python your_app.py
  """

[build.environment]
  PYTHON_VERSION = "3.8.18"
