[build]
  command = """
    unset MISE_PYTHON_VERSION
    rm -rf ~/.cache/mise
    export PATH=$(echo $PATH | sed -E 's|:/opt/buildhome/.mise/bin||g')

    export PYENV_ROOT="$HOME/.pyenv"
    curl https://pyenv.run | bash
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)"
    eval "$(pyenv virtualenv-init -)"

    latest_python=$(pyenv install --list | grep -E '^[0-9]+\\.[0-9]+\\.[0-9]+$' | tail -1)
    pyenv install -s $latest_python
    pyenv global $latest_python

    python --version
    pip install --upgrade pip
    pip install -r requirements.txt
    python your_app.py
  """
